select setval('admissions_admission_id_seq',(select max(admission_id) from admissions));
select setval(' cess_agreement_histories_cess_agreement_history_id_seq',(select max(cess_agreement_history_id) from  cess_agreement_histories));
select setval(' karte_communications_karte_communication_id_seq',(select max(karte_communication_id) from  karte_communications));
select setval(' mini_cex_learning_challenges_mini_cex_learning_challenge_id_seq',(select max(mini_cex_learning_challenge_id) from  mini_cex_learning_challenges));
select setval(' mini_cex_mini_cex_id_seq',(select max(mini_cex_id) from  mini_cex));
select setval(' nursing_related_chart_lock_hi_nursing_related_chart_lock_hi_seq',(select max(nursing_related_chart_lock_history_id) from nursing_related_chart_lock_histories));
select setval(' nursing_related_chart_snapsho_nursing_related_chart_snapsho_seq',(select max(nursing_related_chart_snapshot_id) from nursing_related_chart_snapshots));
select setval(' reference_documents_reference_document_id_seq',(select max(reference_document_id) from  reference_documents));
select setval(' subject_patients_subject_patient_id_seq',(select max(subject_patient_id) from  subject_patients));
select setval(' submitted_reports_submitted_report_id_seq',(select max(submitted_report_id) from  submitted_reports));
select setval(' trainee_evaluations_trainee_evaluation_id_seq',(select max( trainee_evaluation_id) from trainee_evaluations));
select setval(' trainee_patient_assignment_sh_trainee_patient_assignment_sh_seq',(select max(trainee_patient_assignment_shift_id) from trainee_patient_assignment_shifts));
select setval(' trainee_patient_assignments_trainee_patient_assignment_id_seq',(select max(trainee_patient_assignment_id) from  trainee_patient_assignments));
select setval(' training_dept_evaluations_training_dept_evaluation_id_seq',(select max(training_dept_evaluation_id) from  training_dept_evaluations));
select setval(' training_me_practice_history_id_seq',(select max(training_medical_exercise_practice_history_id) from training_medical_exercise_practice_histories));
select setval(' training_related_document_loc_training_related_document_loc_seq',(select max(training_related_document_lock_history_id) from training_related_document_lock_histories));
select setval(' training_related_document_sna_training_related_document_sna_seq',(select max(training_related_document_snapshot_id) from training_related_document_snapshots));
select setval(' training_reports_training_report_id_seq',(select max(training_report_id) from  training_reports));
select setval(' user_memos_user_memo_id_seq',(select max(user_memo_id) from  user_memos));
select setval(' user_templates_user_id_seq',(select max(user_id) from  user_templates));
select setval(' users_user_id_seq',(select max(user_id) from  users));

